### model
model_name_or_path: /file/tian/models/llava-v1.6-vicuna-7b-hf

### dataset
dataset: llavadata
dataset_dir: config
template: llava_next
cutoff_len: 1024
max_samples: 10000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: sft_output/adapter
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all
# deepspeed: config/ds_z3_config.json

### train
per_device_train_batch_size: 8
gradient_accumulation_steps: 4
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
