### Note: DO NOT use quantized model or quantization_bit when merging lora adapters

### model
model_name_or_path: /file/models/Qwen2.5-7B-Instruct
adapter_name_or_path: sft_output/adapter
template: qwen
finetuning_type: lora

### export
export_dir: sft_output/model
export_size: 2
export_device: cpu
export_legacy_format: false
